openapi: 3.1.2
info:
  title: Book Publishing API Catalog
  version: 0.1.0
  description: |-
    Public API for consuming information about books, authors, and collections in a publishing system.
    This API provides read-only operations for books, collections and authors.
  contact:
    name: FrancescFe
    url: https://github.com/FrancescFe
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://localhost:8080
    description: local server

paths:
  /api/v1/books:
    get:
      tags:
        - ListBooksPaginated
      operationId: listBooksPaginated
      summary: List books with pagination
      description: Retrieve a paginated list of books.
      parameters:
        - $ref: './shared/components/parameters/pagination.yaml#/limit'
        - $ref: './shared/components/parameters/pagination.yaml#/page'
      responses:
        '200':
          $ref: './book/components/responses/books-list-paginated.yaml'
        '400':
          $ref: './shared/components/responses/errors/bad-request.yaml'
        '500':
          $ref: './shared/components/responses/errors/internal-error.yaml'
