name: Code Formatting Check

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.kt'
      - '**/*.kts'
      - '**/*.java'
      - '**/*.gradle'
      - '**/*.gradle.kts'
      - '.editorconfig'
      - 'build.gradle.kts'
  push:
    branches: [ main ]
    paths:
      - '**/*.kt'
      - '**/*.kts'
      - '**/*.java'
      - '**/*.gradle'
      - '**/*.gradle.kts'
      - '.editorconfig'
      - 'build.gradle.kts'

jobs:
  format-check:
    runs-on: ubuntu-latest
    name: Check Code Formatting

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper

      - name: Check code formatting
        run: ./gradlew spotlessCheck
