name: Validate OpenAPI Specification

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'specs/**/*.yaml'
      - 'specs/**/*.yml'
      - 'build.gradle.kts'
  push:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate OpenAPI Spec

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          cache-read-only: false

      - name: Validate OpenAPI specification
        run: ./gradlew openApiValidate

      - name: Generate API code (test)
        run: ./gradlew openApiGenerate
