name: Validate Gradle Build

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'specs/**/*.yaml'
      - 'specs/**/*.yml'
      - 'build.gradle.kts'
  push:
    branches: [ main ]

jobs:
  build-and-compile:
    runs-on: ubuntu-latest
    name: Build and Compile Validation

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          cache-read-only: false

      - name: Build project
        run: ./gradlew build
